# Generated by Django 4.2.4 on 2023-08-24 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="courses",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contents",
                to="courses.course",
            ),
        ),
    ]
