# Generated by Django 4.2.4 on 2023-08-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="video_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
