# Generated by Django 4.2.4 on 2023-08-28 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0003_alter_content_video_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="courses",
            new_name="course",
        ),
    ]
