# Generated by Django 4.2.4 on 2023-08-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_alter_course_instructor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("not started", "Default"),
                    ("in progress", "In Progress"),
                    ("finished", "Finished"),
                ],
                default="not started",
                max_length=11,
            ),
        ),
    ]
