# Generated by Django 4.2.4 on 2023-08-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_alter_course_end_date_alter_course_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="end_date",
            field=models.DateField(),
        ),
    ]
